apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app

resources:
- ../../../../../app/base

patches:
  - path: image-version-patch.yml
    target:
      kind: Deployment
      name: app
  - path: replicas-patch.yml
    target:
      kind: Deployment
  - path: ingress-patch.yml
    target:
      kind: Ingress